<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Todo list')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->setAutoEscape(false)
    ?>

    <!-- Le styles -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/materialize.min.css'))
        ->setAutoEscape(false)
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/materialize.min.js'))
        ->setAutoEscape(false)
    ?>

</head>
<body>
<nav class="teal lighten-2" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="<?= $this->basePath() ?>" class="brand-logo">Todo-list</a>
    </div>
</nav>

<main>
    <div class="container">
        <?= $this->content ?>
    </div>
</main>


<footer class="page-footer teal lighten-2">
    <div class="container">
        <div class="row center-align">
            © 2019 Dragomir Angelov
        </div>
    </div>
</footer>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/main.js'))
    ->setAutoEscape(false)
?>

</body>
</html>
