<div class="section">
    <div class="row">
        <div class="col s12 l8 xl6 offset-l2 offset-xl3">
            <div class="card">
                <div class="card-content">
                    <h6 class="card-title center-align bigTitle">Todo-list</h6>

                    <form id="addTaskForm" action="<?= $this->url('home/create') ?>" method="post"
                          onsubmit="handleAddTask(event, this)">
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="title" type="text" name="title">
                                <label for="title">Title</label>
                            </div>
                        </div>
                    </form>

                    <div id="tempTask" class="task hide">
                        <div class="row">
                            <div class="col s12">
                                <label class="active">
                                    <input type="checkbox" name="completed">
                                    <span class="taskTitle"></span>
                                </label>
                                <button class="deleteTaskButton btn-small btn-floating right"
                                        data-action="<?= $this->url('home/delete', ['id' => 'tempTaskId']); ?>">
                                    <i class="material-icons">delete</i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div id="taskList">
                        <!-- Insert tasks here -->
                        <?php foreach ($this->tasks as $task) : ?>
                            <div id="<?= $task['id'] ?>" class="task">
                                <div class="row">
                                    <div class="col s12">
                                        <label class="active">
                                            <input type="checkbox" name="completed" <?= $task['completed'] ? 'checked' : '' ?>
                                                   onclick="handleUpdateTask(event, '<?= $this->url('home/update', ['id' => $task['id']]); ?>')">
                                            <span class="taskTitle <?= $task['completed'] ? 'text-line-through' : '' ?>">
                                                <?= $task['title'] ?>
                                            </span>
                                        </label>
                                        <button class="deleteTaskButton btn-small btn-floating right"
                                                onclick="handleRemoveTask('<?= $this->url('home/delete', ['id' => $task['id']]); ?>')">
                                            <i class="material-icons">delete</i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="card-action">
                    <button id="removeCompletedTasks" class="waves-effect waves-light btn"
                            onclick="handleRemoveCompletedTasks('<?= $this->url('home/delete-completed') ?>')">
                        <span class="hide-on-small-only">Remove completed</span>
                        <i class="show-on-small hide-on-med-and-up material-icons">done_all</i>
                    </button>

                    <button id="removeAllTasks" class="waves-effect waves-light btn right"
                            onclick="handleRemoveAllTasks('<?= $this->url('home/delete-all') ?>')">
                        <span class="">Remove all</span>
                        <i class="material-icons right">delete</i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
